import { db, auth } from "./firebase.js";
import {
  collection,
  getDocs,
  doc,
  getDoc,
  setDoc
} from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";

const params = new URLSearchParams(window.location.search);
const courseIdParam = params.get("id");
const lessonCourseId = params.get("course") || courseIdParam;
const lessonIndex = parseInt(params.get("lesson")) || 0;

/* ================= COURSES PAGE ================= */
const recommendedEl = document.getElementById("recommendedCourses");
const allCoursesEl = document.getElementById("allCourses");

if (recommendedEl && allCoursesEl) {
  onAuthStateChanged(auth, async (user) => {
    if (!user) return;
    const userId = user.uid;

    const coursesSnap = await getDocs(collection(db, "courses"));
    const progressSnap = await getDocs(
      collection(db, "userProgress", userId, "courses")
    );

    const progressMap = {};
    progressSnap.forEach(doc => progressMap[doc.id] = doc.data());

    renderCourses(coursesSnap, progressMap);
  });
}

function renderCourses(coursesSnap, progressMap) {
  recommendedEl.innerHTML = "";
  allCoursesEl.innerHTML = "";

  let completed = 0;
  let inProgress = 0;

    recommendedEl.insertAdjacentHTML("beforeend", `
    <div class="premium-card roadmap-card">
      <div class="card-header">
        <i class="fa-solid fa-map-signs" style="color: var(--blue)"></i>
        <span class="premium-badge"><i class="fa-solid fa-lock"></i> Premium</span>
      </div>
      <h4 class="premium-title">Interactive Roadmap</h4>
      <p class="premium-desc">
        Get a personalized learning plan generated by AI to help you reach your goals efficiently and track your progress from beginner to expert.
      </p>
      <span class="stat-pill btn-explore">
        Explore Roadmap <i class="fa-solid fa-arrow-right"></i>
      </span>
    </div>
  `);
  
  coursesSnap.forEach(docSnap => {
    const course = docSnap.data();
    const courseId = docSnap.id;
    const progress = progressMap[courseId];

    let progressHTML = "";
    let buttonHTML = `<button class="btn" onclick="location.href='course.html?id=${courseId}'"><i class="fa-solid fa-rocket"></i> Start Course</button>`;
    let badgeHTML = "";

    if (progress) {
      progressHTML = `
        <div class="progress">
          <span style="width:${progress.progress}%"></span>
        </div>
        <div class="progress-text">
          ${progress.completedLessons.length}/${course.totalLessons} completed
        </div>
      `;

      if (progress.completed) {
        completed++;
        badgeHTML = `<div class="completed-badge"><i class="fa-solid fa-check"></i></div>`;
        buttonHTML = `<button class="btn alt" onclick="location.href='course.html?id=${courseId}&review=true'"><i class="fa-solid fa-rotate-left"></i> Review Course</button>`;
      } else {
        inProgress++;
        buttonHTML = `<button class="btn" onclick="location.href='course.html?id=${courseId}&resume=true'"><i class="fa-solid fa-play"></i> Continue</button>`;
      }
    }

    const cardHTML = `
      <div class="card">
        <div class="card-header"><i class="fa-solid ${course.icon}" style="color:#facc15"></i>${badgeHTML}</div>
        <h4>${course.title}</h4>
        ${progressHTML}
        <div class="course-meta-row">
          <span class="level ${course.level.toLowerCase()}">${course.level}</span>
          <span class="course-hours"><i class="fa-regular fa-clock"></i> ${course.totalHours}h</span>
        </div>
        ${buttonHTML}
      </div>
    `;

    allCoursesEl.insertAdjacentHTML("beforeend", cardHTML);
    if (progress) recommendedEl.insertAdjacentHTML("beforeend", cardHTML);
  });

  if (inProgress === 0) {
    recommendedEl.innerHTML = `
      <div class="premium-card roadmap-card">
    <div class="card-header">
      <i class="fa-solid fa-map-signs" style="color: var(--blue)"></i>
      <span class="premium-badge"><i class="fa-solid fa-lock"></i> Premium</span>
    </div>
    <h4 class="premium-title">Interactive Roadmap</h4>
    <p class="premium-desc">
      Get a personalized learning plan generated by AI to help you reach your goals efficiently and track your progress from beginner to expert.
    </p>
    <span class="stat-pill btn-explore">
      Explore Roadmap <i class="fa-solid fa-arrow-right"></i>
    </span>
  </div>
      <div class="empty-state">
        <i class="fa-solid fa-seedling"></i>
        <h4>Your learning journey starts here</h4>
        <p>You haven’t started any courses yet.<br>Pick one below and let’s grow together!</p>
      </div>
    `;
  }

  const statCompletedEl = document.querySelector(".stat-completed");
  const statProgressEl = document.querySelector(".stat-progress");
  if (statCompletedEl) statCompletedEl.textContent = `${completed} Completed`;
  if (statProgressEl) statProgressEl.textContent = `${inProgress} In Progress`;
}

/* ================= COURSE PAGE ================= */
if (courseIdParam) {
  onAuthStateChanged(auth, async (user) => {
    if (!user) return;
    const userId = user.uid;

    const courseSnap = await getDoc(doc(db, "courses", courseIdParam));
    if (!courseSnap.exists()) return;
    const course = courseSnap.data();

    const progressRef = doc(db, "userProgress", userId, "courses", courseIdParam);
    const progressSnap = await getDoc(progressRef);
    let progress = progressSnap.exists() ? progressSnap.data() : { completedLessons: [], lastLesson: -1, progress: 0, completed: false };
    let quizTimer = null;
    let attemptsCount = 0;
    // Update course info
    document.getElementById("courseTitle").textContent = course.title;
    document.getElementById("courseHours").textContent = `${course.totalHours} hours`;
    document.getElementById("courseCompleted").textContent = `${progress.completedLessons.length} / ${course.totalLessons} completed`;
    document.getElementById("courseDescription").textContent = course.description;

    const percent = Math.round((progress.completedLessons.length / course.totalLessons) * 100);
    document.getElementById("coursePercent").textContent = `${percent}%`;
    document.getElementById("courseProgressBar").style.width = `${percent}%`;

    // Render lessons
    const lessonsEl = document.getElementById("lessonsList");
    if (lessonsEl) {
      lessonsEl.innerHTML = "";
      const lessonsSnap = await getDocs(collection(db, "courses", courseIdParam, "lessons"));
      let lessonIndexLocal = 0;
      lessonsSnap.forEach(docSnap => {
        const lesson = docSnap.data();
        const done = progress.completedLessons.includes(lessonIndexLocal);

        lessonsEl.insertAdjacentHTML("beforeend", `
          <div class="lesson-row ${done ? "active" : ""}" onclick="location.href='lesson.html?course=${courseIdParam}&lesson=${lessonIndexLocal}'">
            <div class="status ${done ? "complete" : "play"}"><i class="fa-solid ${done ? "fa-check" : "fa-play"}"></i></div>
            <div class="lesson-info">
              <h4>${lesson.title}</h4>
              <span><i class="fa-regular fa-clock"></i> ${lesson.duration}</span>
            </div>
          </div>
        `);
        lessonIndexLocal++;
      });
    }

    // Check completion
    if (progress.completedLessons.length === course.totalLessons && !progress.completed) {
      progress.completed = true;
      await setDoc(progressRef, progress);

      const cardHeader = document.querySelector(".card-header");
      if (cardHeader && !cardHeader.querySelector(".completed-badge")) {
        const badge = document.createElement("div");
        badge.className = "completed-badge";
        badge.innerHTML = '<i class="fa-solid fa-check"></i>';
        cardHeader.appendChild(badge);
      }

      const continueBtn = document.querySelector(".btn");
      if (continueBtn) {
        continueBtn.classList.add("alt");
        continueBtn.innerHTML = `<i class="fa-solid fa-rotate-left"></i> Review Course`;
        continueBtn.onclick = () => location.href = `course.html?id=${courseIdParam}&review=true`;
      }
    }

    // test
    const testSection = document.getElementById("test");
    if (testSection) {
      testSection.innerHTML = "";
      if (progress.completedLessons.length === course.totalLessons) {
        const testSnap = await getDoc(doc(db, "courses", courseIdParam, "test", "test"));
        if (testSnap.exists()) {
          const quiz = testSnap.data();
          const testScoreRef = doc(db, "userProgress", userId, "courses", courseIdParam);
          const testScoreSnap = await getDoc(testScoreRef);
          let previousScore = 0;
          if (testScoreSnap.exists() && testScoreSnap.data().testScore !== undefined) {
            previousScore = testScoreSnap.data().testScore;
          }

        testSection.innerHTML = `
          <h3>${quiz.title}</h3>

          <div style="margin-bottom:12px">
            <div class="level ${course.level.toLowerCase()}" 
                style="font-size:14px; font-weight:600; padding:6px 12px; border-radius:999px; display:inline-block; margin-bottom:8px">
              ${course.level}
            </div>

            <div class="course-hours" style="font-size:14px; display:inline-block; margin-bottom:8px">
              <i class="fa-regular fa-clock"></i> ${quiz.timeMinutes} min
            </div>
          </div>

          <p>Number of questions: ${quiz.numQuestions}</p>
          ${previousScore > 0 ? `<p>Highest Score: ${previousScore}%</p>` : ""}

          <button class="btn" id="startTestBtn" style="background:#0073e6">
            ${previousScore > 0 ? "Retake Test" : "Start Test"}
          </button>

          <div id="quizContainer" class="hidden"></div>
        `;



          document.getElementById("startTestBtn").onclick = () => startQuiz(quiz, previousScore, testScoreRef);
        }
      } else {
        testSection.innerHTML = `<p>Complete all lessons to unlock the test.</p>`;
      }
    }

    function startQuiz(quiz, previousScore = 0, testScoreRef) {
      const testSection = document.getElementById("test");
      if (!testSection) return;

attemptsCount++;

let timeLeft = quiz.timeMinutes * 60;

testSection.innerHTML = `
<div class="quiz-header">
  <h3>${quiz.title}</h3>

  <div class="quiz-badges">
    <div class="quiz-badge timer">
      <i class="fa-regular fa-clock"></i>
      <span id="quizTimer">${quiz.timeMinutes}:00</span>
    </div>

    <div class="quiz-badge attempts">
      <i class="fa-solid fa-repeat"></i>
      Attempt ${attemptsCount}
    </div>
  </div>
</div>


  <div class="quiz-box" >
    ${quiz.questions.map((q, qi) => `
      <div class="question-card">
        <h4>${qi + 1}. ${q.q}</h4>
        <div class="options">
          ${q.options.map((opt, oi) => `
            <label class="option">
              <input type="radio" name="q${qi}" value="${oi}">
              <span>${opt}</span>
            </label>
          `).join("")}
        </div>
      </div>
    `).join("")}

    <div style="display:flex; justify-content:flex-end; margin-top:16px">
      <button
        class="btn submit-btn"
        id="submitQuizBtn"
        style="padding:8px 16px; font-size:13px; background:#0073e6"
      >
        Submit
      </button>
    </div>
        <div id="quizResult"></div>
      </div>
    `;

const timerEl = document.getElementById("quizTimer");

quizTimer = setInterval(() => {
  timeLeft--;
  const min = Math.floor(timeLeft / 60);
  const sec = timeLeft % 60;
  timerEl.textContent = `${min}:${sec.toString().padStart(2, "0")}`;

  if (timeLeft <= 0) {
    clearInterval(quizTimer);
    document.getElementById("submitQuizBtn").click();
  }
}, 1000);


      document.getElementById("submitQuizBtn").onclick = async () => {
         clearInterval(quizTimer);
        let score = 0;
        quiz.questions.forEach((q, qi) => {
          const selected = document.querySelector(`input[name="q${qi}"]:checked`);
          if (selected && Number(selected.value) === q.answer) score++;
        });

        const percent = Math.round((score / quiz.questions.length) * 100);
        document.querySelectorAll(".question-card").forEach(q => q.style.display = "none");
        document.getElementById("submitQuizBtn").style.display = "none";

        const newScore = Math.max(previousScore, percent);
        await setDoc(testScoreRef, { testScore: newScore }, { merge: true });

        const resultBox = document.getElementById("quizResult");
        if (!resultBox) return;

        if (percent >= 60) {
          resultBox.innerHTML = `
            <div class="result success">
              🎉
              <h3>Congratulations!</h3>
              <p>You passed the test!</p>
              <strong>${score}/${quiz.questions.length} (${percent}%)</strong>
            </div>
          `;
        } else {
          resultBox.innerHTML = `
  <div class="result fail">
    <h3>Almost there!</h3>
    <p>Don’t give up — practice makes perfect</p>
    <strong>${score}/${quiz.questions.length} (${percent}%)</strong>
          </br>
    <button class="btn alt" id="redoTestBtn" style="margin-top:14px">
      <i class="fa-solid fa-rotate-right"></i> Retry Test
    </button>
  </div>
`;

document.getElementById("redoTestBtn").onclick = () => {
  clearInterval(quizTimer);
  startQuiz(quiz, previousScore, testScoreRef);
};

        }

        const startBtn = document.getElementById("startTestBtn");
        if (startBtn) {
          startBtn.textContent = "Retake Test";
          startBtn.style.display = "inline-block";
          startBtn.onclick = () => startQuiz(quiz, newScore, testScoreRef);
        }
      };
    }
  });
}

/* ================= LESSON PAGE ================= */
if (lessonCourseId) {
  onAuthStateChanged(auth, async (user) => {
    if (!user) return;
    const userId = user.uid;

    const courseSnap = await getDoc(doc(db, "courses", lessonCourseId));
    if (!courseSnap.exists()) return;
    const course = courseSnap.data();

    const lessonsSnap = await getDocs(collection(db, "courses", lessonCourseId, "lessons"));
    const lessons = [];
    lessonsSnap.forEach(doc => lessons.push(doc.data()));
    const lesson = lessons[lessonIndex];

    function getEmbedUrl(url) {
      if (!url) return "https://www.youtube.com/embed/dQw4w9WgXcQ";
      if (url.includes("youtu.be/")) {
        const id = url.split("/").pop().split("?")[0];
        return `https://www.youtube.com/embed/${id}`;
      }
      if (url.includes("watch?v=")) {
        const id = url.split("v=")[1].split("&")[0];
        return `https://www.youtube.com/embed/${id}`;
      }
      return url;
    }

    // Update lesson page
    const sectionTitle = document.querySelector(".section-title");
    const subtext = document.querySelector(".subtext");
    const lessonTitle = document.querySelector("h3");
    const iframe = document.querySelector(".video-wrapper iframe");

    if (sectionTitle) sectionTitle.textContent = course.title;
    if (subtext) subtext.textContent = `Lesson ${lessonIndex+1} of ${course.totalLessons}`;
    if (lessonTitle) lessonTitle.textContent = lesson.title;
    if (iframe) iframe.src = getEmbedUrl(lesson.videoUrl);

    // Update progress
    const progressRef = doc(db, "userProgress", userId, "courses", lessonCourseId);
    const progressSnap = await getDoc(progressRef);
    let progress = progressSnap.exists() ? progressSnap.data() : { completedLessons: [], lastLesson: -1, progress: 0, completed: false };
    if (!progress.completedLessons.includes(lessonIndex)) {
      progress.completedLessons.push(lessonIndex);
      progress.lastLesson = lessonIndex;
      progress.progress = Math.round((progress.completedLessons.length / course.totalLessons) * 100);
      if (progress.completedLessons.length === course.totalLessons) progress.completed = true;
      await setDoc(progressRef, progress);
    }

    const prevBtn = document.querySelector(".btn.alt");
    const nextBtn = document.querySelector(".btn:not(.alt)");

    if (prevBtn) {
      prevBtn.disabled = lessonIndex === 0;
      prevBtn.onclick = () => window.location.href = `lesson.html?course=${lessonCourseId}&lesson=${lessonIndex-1}`;
    }

    if (nextBtn) {
      if (lessonIndex === course.totalLessons - 1) {
        nextBtn.textContent = "Go to Test";
        nextBtn.onclick = () => window.location.href = `course.html?id=${lessonCourseId}#test`;
      } else {
        nextBtn.textContent = "Next Lesson";
        nextBtn.onclick = () => window.location.href = `lesson.html?course=${lessonCourseId}&lesson=${lessonIndex+1}`;
      }
    }
  });
}
